#!/usr/bin/env bash

set -u

SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
FORCE=false

function main() {
    detect_force "$@"

    install_packages
    install_oh_my_zsh
    #install_zsh_sync
    install_theo_tools
    install_giantswarm_tools
    install_completion
    install_vim_config
    set_shell

    _printf "> install successful!"
    echo "> restart shell"
    exec -l /bin/zsh
}

function _printf() {
    fmt="%-30s%-12s%-12s\n"
    printf ${fmt} "$@"
}

function ask() {
    if ${FORCE}; then
        _printf "> $1 (forced)"
        return 0
    fi

    read -n1 -p "> $1 ? [yN] " REPLY
    _printf
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        return 0
    else
        return 1
    fi
}

function detect_force() {
    if [ $# -gt 0 ]; then
        if [ "${1}" == "-f" ]; then
            FORCE=true
        fi
    fi
}

function detect_os() {
    _printf "> detect os"
    # [[ "$OSTYPE" == "linux-gnu" ]]
    # [[ "$OSTYPE" == "darwin"* ]]
}

function install_packages() {
    if ! ask "install packages"; then
        return 0
    fi

    case "$OSTYPE" in
      darwin*)
        _printf "> osx not implemented yet" ;;
      linux*)
        if [ -f "/etc/arch-release" ]; then
            _printf "> install packages for arch linux"
            install_packages_arch
        else
            _printf "> supported linux (arch)"
        fi ;;
      *)
        _printf "> unsupported os: ${$OSTYPE}" ;;
    esac
}

function install_packages_arch() {
    install_packages_arch_pacman
    install_packages_arch_aur
}

function install_packages_arch_pacman() {
    local packages=""

    for file in $(ls $HOME/.yadm/packages/arch/pacman/); do
        if ask "install pacman ${file}"; then
            packages="${packages}
$(cat "$HOME/.yadm/packages/arch/pacman/${file}")"
        fi
    done

    if [ -n "${packages}" ]; then
        sudo pacman -Sy --noconfirm ${packages}
    fi
}

function install_packages_arch_aur() {
    if ! command -v yay; then
        install_yay
    fi

    local packages=""

    for file in $(ls $HOME/.yadm/packages/arch/aur/); do
        if ask "install aur ${file}"; then
            packages="${packages}
$(cat "$HOME/.yadm/packages/arch/aur/${file}")"
        fi
    done

    if [ -n "${packages}" ]; then
        yay -Sy --noconfirm ${packages}
    fi
}

function install_yay() {
    # install yay
    cd /tmp
    pacman -S --needed git base-devel
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si

}

function install_oh_my_zsh() {
    _printf "> install oh-my-zsh"
    if [ ! -e "$HOME/.config/zsh/oh-my-zsh" ]; then
        git clone https://github.com/robbyrussell/oh-my-zsh.git "$HOME/.config/zsh/oh-my-zsh"
    else
        _printf "> oh-my-zsh installed in" "$HOME/.config/zsh/oh-my-zsh"
    fi
}

function install_zsh_sync() {
    _printf "> install crontab for zsh history sync"
    crontab "${SCRIPT_DIR}/zsh_sync_cronjob"
}

function install_theo_tools() {
    if ! ask "install theo tools"; then
        return 0
    fi

    _printf "> install golang.org/x/lint/golint"
    go install golang.org/x/lint/golint@latest
}


function install_giantswarm_tools() {
    if ! ask "install giantswarm tools"; then
        return 0
    fi

    _printf "> install github.com/giantswarm/opsctl"
    cd /tmp
    rm -rf opsctl
    release=$(curl -sL -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/giantswarm/opsctl/releases/latest | grep tag_name | cut -d '"' -f 4)
    git clone -b $release --depth 1 -c advice.detachedHead=false git@github.com:giantswarm/opsctl.git
    cd opsctl
    go install

    _printf "> install github.com/giantswarm/gsctl"
    rm -rf gsctl
    release=$(curl -sL -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/giantswarm/gsctl/releases/latest | grep tag_name | cut -d '"' -f 4)
    git clone -b $release --depth 1 -c advice.detachedHead=false git@github.com:giantswarm/gsctl.git
    cd gsctl
    go install

    _printf "> install github.com/giantswarm/luigi"
    go install github.com/giantswarm/luigi@latest

    _printf "> install github.com/giantswarm/e2e-harness"
    go install github.com/giantswarm/e2e-harness@latest
}

function install_completion() {
    if ! ask "install completion"; then
        return 0
    fi

    local bash_completion=".local/share/bash-completion/completions"
    local zsh_completion=".config/zsh/completion"

    opsctl completion bash > "${bash_completion}/opsctl"
    opsctl completion zsh > "${zsh_completion}/_opsctl"

    gsctl completion bash --stdout > "${bash_completion}/gsctl"
    gsctl completion zsh --stdout > "${zsh_completion}/gsctl"

    helm completion bash > "${bash_completion}/helm"
    helm completion zsh > "${zsh_completion}/_helm"

    kubectl completion bash > "${bash_completion}/kubectl"
    kubectl completion zsh > "${zsh_completion}/_kubectl"

    minikube completion bash > "${bash_completion}/minikube"
    minikube completion zsh > "${zsh_completion}/_minikube"
}

function install_vim_config() {
    if ! ask "install vim config"; then
        return 0
    fi
    git clone https://github.com/TheoBrigitte/vim.git ~/.vim
}

function set_shell() {
    if ! ask "set default shell to zsh"; then
        return 0
    fi
    chsh --shell /bin/zsh
}

main "$@"
