#!/bin/bash

gi() {
    cd $GOPATH/src/github.com/giantswarm/$1
}

giget() {
    go get -v -d github.com/giantswarm/$1
}

trysource () {
    for var in "$@"; do
        if [ -r "$var" ]; then
            source "$var"
            return
        fi
    done
}

