#!/usr/bin/env bash
_gi_get()
{
	local time=$(date +%s)
	local cache_duration=86400
	local cache_expiry=$((${time}-${cache_duration}))
	local cache_file="$(dirname $(mktemp -u))/g8s-get-cache"

	if [ ! -e "${cache_file}" ] || [ $(stat -c %Y ${cache_file}) -le ${cache_expiry} ]; then
		gile -org giantswarm > "${cache_file}"
	fi

	local cur=${COMP_WORDS[COMP_CWORD]}
	COMPREPLY=( $(compgen -W "$(cat ${cache_file})" -- $cur) )
}

complete -F _gi_get gi-get
