#!/bin/sh

notify_send() {
    #Detect the name of the display in use
    local display=":$(ls /tmp/.X11-unix/* | sed 's#/tmp/.X11-unix/X##' | head -n 1)"

    #Detect the user using such display
    local user=$(who | grep '('$display')' | awk '{print $1}' | head -n 1)

    #Detect the id of the user
    local uid=$(id -u $user)

    sudo -u $user DISPLAY=$display DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$uid/bus notify-send "$@"
}

case "$2" in
    up)
        NEW_TIMEZONE=$(tzupdate --print-only)
        CURRENT_TIMEZONE=$(timedatectl show --property Timezone --value)
        if [ -n "$NEW_TIMEZONE" ] && [ "$NEW_TIMEZONE" != "$CURRENT_TIMEZONE" ]; then
            timedatectl set-timezone "$NEW_TIMEZONE"
            notify_send "Timezone changed - $NEW_TIMEZONE"
        fi
    ;;
esac
