#!/bin/bash

gi() {
    cd $GOPATH/src/github.com/giantswarm/$1
}

giget() {
    go get -v -d github.com/giantswarm/$1
}

replace () {
    local a=$1
    shift
    local b=$1
    shift
    local dir=$1
    shift
    local a="${a//\//\\/}"
    local b="${b//\//\\/}"
    for file in $(find $dir \( -path ./.git -o -path ./vendor \)  -prune -o -type f -print)
    do
        sed -i -e "s/${a}/${b}/g" $file
    done
}

trysource () {
    for var in "$@"; do
        if [ -r "$var" ]; then
            source "$var"
            return
        fi
    done
}
