name: jackett
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - AUTO_UPDATE=true
      - RUN_OPTS= #optional
    volumes:
      - $PWD:/config
    ports:
      - 9117:9117
    networks:
      default: null
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Paris
    ports:
      - 8191:8191
    networks:
      default: null
    restart: unless-stopped
networks:
  default:
    name: jackett_default
