#!/usr/bin/env bash

set -eu

SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
FORCE=false

function main() {
    detect_force "$@"

    install_oh_my_zsh
    install_theo_tools
    install_giantswarm_tools
    install_completion

    _printf "> install successful!"

    echo "> restart: ${SHELL}"
    exec -l $SHELL
}

function _printf() {
    fmt="%-30s%-12s%-12s\n"
    printf ${fmt} "$@"
}

function ask() {
    if ${FORCE}; then
        _printf "> $1 (forced)"
        return 0
    fi

    read -n1 -p "> $1 ? [yN] " REPLY
    _printf
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        return 0
    else
        return 1
    fi
}

function detect_force() {
    if [ $# -gt 0 ]; then
        if [ "${1}" == "-f" ]; then
            FORCE=true
        fi
    fi
}

function goinstall() {
    go install "${1}"
}

function install_oh_my_zsh() {
    if [ ! -e "$HOME/.config/zsh/oh-my-zsh" ]; then
        git clone https://github.com/robbyrussell/oh-my-zsh.git "$HOME/.config/zsh/oh-my-zsh"
    else
        _printf "> oh-my-zsh installed in" "$HOME/.config/zsh/oh-my-zsh"
    fi
}

function install_theo_tools() {
    if ! ask "install theo tools"; then
        return 0
    fi

    _printf "> install github.com/TheoBrigitte/gile"
    go install github.com/TheoBrigitte/gile

    _printf "> install golang.org/x/lint/golint"
    go get -u golang.org/x/lint/golint
}


function install_giantswarm_tools() {
    if ! ask "install giantswarm tools"; then
        return 0
    fi

    _printf "> install github.com/giantswarm/opsctl"
    go install github.com/giantswarm/opsctl

    _printf "> install github.com/giantswarm/gsctl"
    go install github.com/giantswarm/gsctl

    _printf "> install github.com/giantswarm/luigi"
    go install github.com/giantswarm/luigi

    _printf "> install github.com/giantswarm/e2e-harness"
    go install github.com/giantswarm/e2e-harness
}

function install_completion() {
    if ! ask "install completion"; then
        return 0
    fi

    local bash_completion=".local/share/bash-completion/completions"
    local zsh_completion=".config/zsh/completion"

    opsctl completion bash > "${bash_completion}/opsctl"
    opsctl completion zsh > "${zsh_completion}/_opsctl"

    gsctl completion
    mv gsctl-completion-bash.sh "${bash_completion}/gsctl"
    mv gsctl-completion-zsh.sh "${zsh_completion}/_gsctl"

    helm completion bash > "${bash_completion}/helm"
    helm completion zsh > "${zsh_completion}/_helm"

    kubectl completion bash > "${bash_completion}/kubectl"
    kubectl completion zsh > "${zsh_completion}/_kubectl"

    minikube completion bash > "${bash_completion}/minikube"
    minikube completion zsh > "${zsh_completion}/_minikube"
}

main "$@"
